language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "8"
  - "10"
  - "12"
sudo: required
services: docker
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_BUILD_STAGE_NAME" =~ Test.* ]]; then ./run_docker.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./win_install.bat; fi
install:
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" =~ Test.* ]]; then npm install; fi

script:
  - if [[ "$TRAVIS_BUILD_STAGE_NAME" =~ Test.* ]]; then make lint; make test; make check; else echo $TRAVIS_BUILD_STAGE_NAME; fi

jobs:
  include:
    - stage: test_on_mac
      os: osx
      osx_image: xcode10
      env: CPPFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib
      node_js:
        - "10"
    - stage: test_on_win
      os: windows
      node_js:
        - "10"
    - stage: deploy
      os: linux
      node_js:
        - "10"
      script: skip
      if: (tag =~ ^v)
      before_deploy:
      - npm install --no-save semver
      deploy:
        provider: npm
        email: ci@terascope.io
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
      after_deploy:
        - cat package.json
